set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
include_directories(${REACTOS_SOURCE_DIR}/sdk/include/reactos/rwm)
include_directories(${REACTOS_SOURCE_DIR}/win32ss/dwm/shared/include)
include_directories(${REACTOS_SOURCE_DIR}/win32ss/dwm/shared/UtilLib)
include_directories(${REACTOS_SOURCE_DIR}/win32ss/dwm/milcore_include)
include_directories(${REACTOS_SOURCE_DIR}/win32ss/dwm/dwm/shared/LpcCreateLib)

list(APPEND SOURCE
    LpcCreateLib.cpp
    )

add_library(LpcCreateLib ${SOURCE})
add_dependencies(LpcCreateLib xdk)

target_link_libraries(LpcCreateLib PRIVATE cppstl)
