#include <ntoskrnl.h>
#define NDEBUG
#include <debug.h>

#pragma warning( push )
#pragma warning( disable : 4276 )

NTSTATUS NTAPI NtThawRegistry() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtThawTransactions() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtTraceControl() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAddAtomEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAdjustTokenClaimsAndDeviceGroups() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlertThreadByThreadId(PKTHREAD Thread) { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAllocateReserveObject() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcAcceptConnectPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCancelMessage() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcConnectPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcConnectPortEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCreatePort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCreatePortSection() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCreateResourceReserve() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCreateSectionView() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcCreateSecurityContext() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcDeletePortSection() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcDeleteResourceReserve() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcDeleteSectionView() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcDeleteSecurityContext() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcDisconnectPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtAlpcImpersonateClientContainerOfPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcImpersonateClientOfPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcOpenSenderProcess() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcOpenSenderThread() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcQueryInformation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcQueryInformationMessage() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcRevokeSecurityContext() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcSendWaitReceivePort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcSetInformation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAssociateWaitCompletionPacket() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCancelIoFileEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCancelSynchronousIoFile() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtCancelTimer2() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCancelWaitCompletionPacket() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCommitComplete() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCommitEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCommitTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateDirectoryObjectEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtCreateIRTimer() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateKeyTransacted() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateLowBoxToken() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreatePartition() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreatePrivateNamespace() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateProfileEx(_Out_ PHANDLE ProfileHandle,
    _In_ HANDLE ProcessHandle,
    _In_ PVOID ImageBase,
    _In_ SIZE_T ImageSize,
    _In_ ULONG Granularity,
    _Out_ PVOID Buffer,
    _In_ ULONG ProfilingSize,
    _In_ KPROFILE_SOURCE Source,
    _In_ USHORT GroupCount,
    _In_reads_(GroupCount) PGROUP_AFFINITY Affinity) { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateThreadEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateTimer2() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateTokenEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateUserProcess() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateWaitCompletionPacket() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateWnfStateName() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateWorkerFactory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtDeletePrivateNamespace() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtDeleteWnfStateData() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtDeleteWnfStateName() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtDisableLastKnownGood() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtDrawText() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtEnableLastKnownGood() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtEnumerateTransactionObject() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFilterBootOption() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFilterTokenEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFlushBuffersFileEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFlushInstallUILanguage() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFlushProcessWriteBuffers() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFreezeRegistry() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtFreezeTransactions() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetCachedSigningLevel() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetCompleteWnfStateSubscription() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetCurrentProcessorNumberEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetMUIRegistryInfo() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetNextProcess() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetNextThread() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetNlsSectionPtr() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtGetNotificationResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtInitializeNlsFiles() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtIsUILanguageComitted() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtMapCMFModule() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNotifyChangeSession() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenKeyTransacted() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenKeyTransactedEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenPrivateNamespace() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenSession() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPrePrepareComplete() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPrePrepareEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPrefetchVirtualMemory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPrepareComplete() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPrepareEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPropagationComplete() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtPropagationFailed() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryInformationEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryInformationResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryInformationTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryInformationTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryInformationWorkerFactory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryLicenseValue() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQuerySecurityAttributesToken() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQuerySystemInformationEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryWnfStateData() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtQueryWnfStateNameInformation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtReadOnlyEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRecoverEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRecoverResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRecoverTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRegisterProtocolAddressInformation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtReleaseWorkerFactoryWorker() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRemoveIoCompletionEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRenameTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtReplacePartitionUnit() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRollbackComplete() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRollbackEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRollbackTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRollforwardTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSerializeBoot() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationEnlistment() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationResourceManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationTransactionManager() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationWorkerFactory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetIoCompletionEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetSystemCodeIntegrityRoots() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetTimerEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtShutdownWorkerFactory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSinglePhaseReject() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSubscribeWnfStateChange() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtUmsThreadYield() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtUnmapViewOfSectionEx() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtUnsubscribeWnfStateChange() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtUpdateWnfStateData() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtWaitForAlertByThreadId() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtWaitForWnfNotifications() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtWaitForWorkViaWorkerFactory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtReleaseCMFViewOwnership() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtManagePartition() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCallEnclave() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateEnclave() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtInitializeEnclave() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtLoadEnclaveData() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtManagePartition() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtOpenPartition() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtRevertContainerImpersonation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtNtSetCachedSigningLevel() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetIRTimer() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationSymbolicLink() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetInformationVirtualMemory() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetTimer2() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetWnfProcessNotificationEvent() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtAlpcImpersonateClientContainerOfPort() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCancelTimer2() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCreateIRTimer() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtInitializeEnclave() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtLoadEnclaveData() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtRevertContainerImpersonation() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSetCachedSigningLevel() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtSavepointTransaction() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }
NTSTATUS NTAPI NtCompareObjects() { UNIMPLEMENTED; return STATUS_NOT_IMPLEMENTED; }

#pragma warning( pop )