@ stdcall DbgExGetVersion()
@ stdcall DbgExIsFullDebug()
@ stdcall DbgExAddRefDebugLibrary()
@ stdcall DbgExReleaseDebugLibrary()
@ stdcall DbgExSetDllMain(ptr ptr)
@ stdcall DbgExDoTracePointsDialog(long)
@ stdcall DbgExRestoreDefaultDebugState()
@ stdcall DbgExEnableTag(long long)
@ stdcall DbgExSetDiskFlag(long long)
@ stdcall DbgExSetBreakFlag(long long)
@ stdcall DbgExIsTagEnabled(long)
@ stdcall DbgExFindTag()
@ stdcall DbgExTagError()
@ stdcall DbgExTagWarning()
@ stdcall DbgExTagThread()
@ stdcall DbgExTagAssertExit()
@ stdcall DbgExTagAssertStacks()
@ stdcall DbgExTagMemoryStrict()
@ stdcall DbgExTagCoMemoryStrict()
@ stdcall DbgExTagMemoryStrictTail()
@ stdcall DbgExTagMemoryStrictAlign()
@ stdcall DbgExTagOLEWatch()
@ stdcall DbgExTagRegisterTrace(wstr wstr wstr long)
@ stdcall DbgExTaggedTraceListEx(long long long ptr)
@ stdcall DbgExTaggedTraceCallers(long long long)
@ stdcall DbgExAssertThreadDisable(long)
@ stdcall DbgExPreAlloc(long ptr)
@ stdcall DbgExPostAlloc(ptr)
@ stdcall DbgExPreFree(ptr)
@ stdcall DbgExPostFree()
@ stdcall DbgExPreRealloc(ptr long ptr ptr)
@ stdcall DbgExPostRealloc(ptr)
@ stdcall DbgExPreGetSize(ptr)
@ stdcall DbgExPostGetSize(long)
@ stdcall DbgExMtPreAlloc(long ptr)
@ stdcall DbgExMtPostAlloc(ptr)
@ stdcall DbgExMtPreFree(ptr)
@ stdcall DbgExMtPostFree()
@ stdcall DbgExMtPreRealloc(ptr long ptr ptr)
@ stdcall DbgExMtPostRealloc(ptr)
@ stdcall DbgExMtPreGetSize(ptr)
@ stdcall DbgExMtPostGetSize(long)
@ stdcall DbgExMemoryTrackDisable(long)
@ stdcall DbgExCoMemoryTrackDisable(long)
@ stdcall DbgExMemoryBlockTrackDisable(ptr)
@ stdcall DbgExTraceMemoryLeaks()
@ stdcall DbgExValidateKnownAllocations()
@ stdcall DbgExTraceFailL(ptr ptr long long long long)
@ stdcall DbgExTraceWin32L(ptr ptr long long long long)
@ stdcall DbgExTraceHR(ptr long long long long)
@ stdcall DbgExSetSimFailCounts(long)
@ stdcall DbgExShowSimFailDlg(long)
@ stdcall DbgExFFail()
@ stdcall DbgExGetFailCount()
@ stdcall DbgExOpenMemoryMonitor()
@ stdcall DbgExOpenLogFile(ptr)
@ stdcall DbgExDumpProcessHeaps()
@ stdcall DbgExMtRegister(long long long long)
@ stdcall DbgExMtAdd(ptr long long)
@ stdcall DbgExMtSet(ptr long long)
@ stdcall DbgExMtGetName(ptr)
@ stdcall DbgExMtGetDesc(ptr)
@ stdcall DbgExMtGetParent(ptr)
@ stdcall DbgExMtGetFlags(ptr)
@ stdcall DbgExMtSetFlags(ptr long)
@ stdcall DbgExMtSimulateOutOfMemory(ptr long)
@ stdcall DbgExMtOpenMonitor()
@ stdcall DbgExMtLogDump(long)
@ stdcall DbgExMtLookupMeter(long)
@ stdcall DbgExMtGetMeterCnt(ptr long)
@ stdcall DbgExMtGetMeterVal(ptr long)
@ stdcall DbgExMtGetDefaultMeter()
@ stdcall DbgExMtSetDefaultMeter(ptr)
@ stdcall DbgExGetStackAddresses(ptr long long)
@ stdcall DbgExGetChkStkFill(ptr)