@ stdcall MILAddRef(ptr)
@ stdcall MILRelease(ptr)
@ stdcall MILQueryInterface(ptr ptr ptr)
@ stdcall MILCreateFactory(ptr long)
@ stdcall MILFactoryCreateMediaPlayer(ptr ptr long ptr)
@ stdcall MILFactoryCreateSWRenderTargetForBitmap(ptr ptr ptr)
@ stdcall MILFactoryCreateBitmapRenderTarget(ptr long long long long long long ptr)
@ stdcall MILLoadResource(ptr ptr ptr)
@ stdcall MILRenderTargetBitmapGetBitmap(ptr ptr)
@ stdcall MILRenderTargetBitmapClear(ptr)
@ stdcall MILMediaOpen(ptr ptr)
@ stdcall MILMediaStop(ptr)
@ stdcall MILMediaClose(ptr)
@ stdcall MILMediaGetPosition(ptr ptr)
@ stdcall MILMediaSetPosition(ptr double)
@ stdcall MILMediaSetVolume(ptr double)
@ stdcall MILMediaSetBalance(ptr double)
@ stdcall MILMediaSetIsScrubbingEnabled(ptr long)
@ stdcall MILMediaSetRate(ptr double)
@ stdcall MILMediaHasVideo(ptr ptr)
@ stdcall MILMediaHasAudio(ptr ptr)
@ stdcall MILMediaCanPause(ptr ptr)
@ stdcall MILMediaIsBuffering(ptr ptr)
@ stdcall MILMediaGetBufferingProgress(ptr ptr)
@ stdcall MILMediaGetDownloadProgress(ptr ptr)
@ stdcall MILMediaGetNaturalHeight(ptr ptr)
@ stdcall MILMediaGetNaturalWidth(ptr ptr)
@ stdcall MILMediaGetMediaLength(ptr ptr)
@ stdcall MILMediaNeedUIFrameUpdate(ptr)
@ stdcall MILMediaShutdown(ptr)
@ stdcall MILCreateEventProxy(ptr ptr)
@ stdcall MILMediaProcessExitHandler(ptr)
@ stdcall MILSwDoubleBufferedBitmapCreate(long long double double ptr ptr ptr)
@ stdcall MILSwDoubleBufferedBitmapGetBackBuffer(ptr ptr ptr)
@ stdcall MILSwDoubleBufferedBitmapAddDirtyRect(ptr ptr)
@ stdcall MILSwDoubleBufferedBitmapProtectBackBuffer(ptr)
@ stdcall MILCreateStreamFromStreamDescriptor(ptr ptr)
@ stdcall MILIStreamWrite(ptr ptr long ptr)
@ stdcall MILUpdateSystemParametersInfo()
@ stdcall MilVersionCheck(long)
@ stdcall MilCompositionEngine_EnterCompositionEngineLock()
@ stdcall MilCompositionEngine_ExitCompositionEngineLock()
@ stdcall MilCompositionEngine_GetComposedEventId(ptr)
@ stdcall MilConnection_CreateChannel(ptr ptr ptr)
@ stdcall MilConnection_DestroyChannel(ptr)
@ stdcall MilChannel_CommitChannel(ptr)
@ stdcall MilChannel_CloseBatch(ptr)
@ stdcall WgxConnection_Create(long ptr)
@ stdcall WgxConnection_ShouldForceSoftwareForGraphicsStreamClient()
@ stdcall WgxConnection_SameThreadPresent(ptr)
@ stdcall WgxConnection_Disconnect(ptr)
@ stdcall MilCompositionEngine_InitializePartitionManager(ptr)
@ stdcall MilCompositionEngine_UpdateSchedulerSettings(ptr)
@ stdcall MilCompositionEngine_DeinitializePartitionManager()
@ stdcall MilPlayer_Create(ptr)
@ stdcall MilPlayer_Process(ptr ptr ptr ptr long)
@ stdcall MilUtility_GetTileBrushMapping(ptr ptr long long long long long ptr ptr ptr ptr ptr ptr)
@ stdcall MilUtility_CopyPixelBuffer(ptr long long long ptr long long long long long)
@ stdcall MilComposition_SyncFlush(ptr)
@ stdcall MilComposition_PeekNextMessage(ptr ptr long ptr)
@ stdcall MilComposition_WaitForNextMessage(ptr long ptr long long ptr)
@ stdcall MilResource_CreateOrAddRefOnChannel(ptr long ptr)
@ stdcall MilResource_DuplicateHandle(ptr ptr ptr ptr)
@ stdcall MilResource_ReleaseOnChannel(ptr ptr ptr)
@ stdcall MilResource_GetRefCountOnChannel(ptr ptr ptr)
@ stdcall MilChannel_GetMarshalType(ptr ptr)
@ stdcall MilChannel_SetReceiveBroadcastMessages(ptr long)
@ stdcall MilResource_SendCommand(ptr long ptr)
@ stdcall MilChannel_BeginCommand(ptr ptr long long)
@ stdcall MilChannel_AppendCommandData(ptr ptr long)
@ stdcall MilChannel_EndCommand(ptr)
@ stdcall MilResource_CreateCWICWrapperBitmap(ptr ptr)
@ stdcall MilResource_SendCommandBitmapSource(ptr ptr ptr)
@ stdcall MilResource_SendCommandMedia(ptr ptr ptr long)
@ stdcall MilChannel_SetNotificationWindow(ptr ptr long)
@ stdcall MilUtility_ArcToBezier(double double double double double long long double double ptr ptr ptr)
@ stdcall MilUtility_PathGeometryWiden(ptr ptr ptr long ptr long double long ptr ptr)
@ stdcall MilUtility_PathGeometryOutline(ptr long ptr long double long ptr ptr)
@ stdcall MilUtility_GetPointAtLengthFraction(ptr long ptr long double ptr ptr)
@ stdcall MilUtility_PathGeometryCombine(ptr ptr long ptr long ptr long ptr long double long ptr long ptr)
@ stdcall MilUtility_PathGeometryFlatten(ptr long ptr long double long ptr ptr)
@ stdcall MilUtility_PolygonBounds(ptr ptr ptr ptr ptr long long ptr double long long ptr)
@ stdcall MilUtility_PathGeometryBounds(ptr ptr ptr long ptr long ptr double long long ptr)
@ stdcall MilUtility_PolygonHitTest(ptr ptr ptr ptr ptr long long double long ptr ptr)
@ stdcall MilUtility_PathGeometryHitTest(ptr ptr ptr long ptr long double long ptr ptr)
@ stdcall MilUtility_PathGeometryHitTestPathGeometry(ptr long ptr long ptr long ptr long double long ptr)
@ stdcall MilUtility_GeometryGetArea(long ptr long ptr double long ptr)
@ stdcall SetMilPerfInstrumentationFlags(ptr)
@ stdcall MilVisualTarget_AttachToHwnd(ptr)
@ stdcall MilVisualTarget_DetachFromHwnd(ptr)
@ stdcall MilContent_AttachToHwnd(ptr)
@ stdcall MilContent_DetachFromHwnd(ptr)
@ stdcall MIL3DCalcProjected2DBounds(ptr ptr ptr)
@ stdcall InteropDeviceBitmap_Create(ptr double double long ptr long ptr ptr ptr)
@ stdcall InteropDeviceBitmap_Detach(ptr)
@ stdcall InteropDeviceBitmap_AddDirtyRect(long long long long ptr)
@ stdcall InteropDeviceBitmap_GetAsSoftwareBitmap(ptr ptr)
@ stdcall MilGlyphRun_GetGlyphOutline(ptr long long double ptr ptr ptr)
@ stdcall MilGlyphRun_ReleasePathGeometryData(ptr)
@ stdcall IWICColorContext_GetProfileBytes_Proxy(ptr long ptr ptr)
@ stdcall IWICColorContext_GetType_Proxy(ptr ptr)
@ stdcall IWICColorContext_GetExifColorSpace_Proxy(ptr ptr)
@ stdcall GetNextPerfElementId()
@ stdcall RenderOptions_ForceSoftwareRenderingModeForProcess(ptr)
@ stdcall RenderOptions_IsSoftwareRenderingForcedForProcess()
@ stdcall MilTransport_AddRef(ptr)
@ stdcall MilTransport_Create(ptr ptr ptr ptr)
@ stdcall MilTransport_CreateTransportParameters(ptr)
@ stdcall MilTransport_CreateFromPacketTransport(ptr ptr ptr)
@ stdcall MilTransport_CreateSurfaceManager(ptr)
@ stdcall MilTransport_DisconnectTransport(ptr)
@ stdcall MilTransport_InitializeConnectionManager(ptr ptr)
@ stdcall MilTransport_ShutDownConnectionManager(ptr)
@ stdcall MilGraphicsStream_Close(ptr)
@ stdcall MilGraphicsStream_Open(ptr ptr ptr)
@ stdcall MilGraphicsStream_SetTransformHint(ptr)
@ stdcall MilGraphicsStream_GetTransformHint(long ptr)
